import { AntdRegistry } from "@ant-design/nextjs-registry";
import type { Metadata } from "next";

import "./globals.scss";
import RouterProvider from "@/components/provider/RouterProvider";
import ConfigProvider from "@/components/provider/ConfigProvider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
	<html lang="zh-CN">
		<body>
			<AntdRegistry>
				<ConfigProvider>
					<RouterProvider />
					{children}
				</ConfigProvider>
			</AntdRegistry>
		</body>
	</html>
);
export default RootLayout;
