import { AntdRegistry } from "@ant-design/nextjs-registry";
import type { Metadata } from "next";

import "./globals.scss";
import RouterProvider from "@/components/RouterProvider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
	<html lang="zh-CN">
		<body>
			<AntdRegistry>
				<RouterProvider />
				{children}
			</AntdRegistry>
		</body>
	</html>
);
export default RootLayout;
